package com.tima.admin.enums;


import lombok.AllArgsConstructor;
import lombok.Getter;

@AllArgsConstructor
@Getter
public enum CodeNoEnum {
	USER_ADDREEE("AD01"),
	USER_BASE_INFORMATION("AD02"),
	IMAGE_RELATION("AD03"),
	USER_ROLE("AD04"),
	USER_ROLE_RELATION("AD05"),
	USER_PERMISSIONS_INFO("AD06"),
	USER_MENU_INFO("AD07"),
	MENU_PERMISSIONS_RELATION("AD08"),
	THIRD_PARTY_REQUEST("AD09"),
	RECOMMENDED_CODE("AD10"),
	THIRD_PARTY_USER_BASE_INFORMATION("AD11"),
	DEVICE_VERSION_RECORD("AD12"),
	VERSION_RECORD("AD13"),
	SEND_MESSAGE("AD14"),
	LABEL_ATTRIBUTE("AD15"),
	LABEL_ENTITY("AD16"),
	LABEL_INFO("AD17"),
	USER_BINDING_OTHER_MODULES("AD18"),
	LEVEL_CHANGES_RECORD("AD19"),
	ADVERTISING_MANAGEMENT("AD20"),
	THIRD_PARTY_USER_LOGIN("AD21")
	;
	
	private String tableNO;
	
	
}
